name: aplikasi_pendaftaran_siswa
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.1.1
  easy_image_viewer: ^1.2.0
  email_validator: ^2.1.17
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  get_storage: ^2.1.1
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true
